"""Phase 8: build every figure and LaTeX table from the results CSVs.

    python -m research.analysis.make_all --config configs/analysis.yaml

Writes results/summaries/figures/{headline_accuracy_vs_gap,perturbation_gaps}.(pdf|png)
and results/summaries/tables/{main,extraction,ablations,selection}.tex, plus
results/summaries/README.md listing them. Inputs come from configs/analysis.yaml;
runs made with --subset are labelled PRELIMINARY on the outputs.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from research.common.cli import base_parser, setup_run
from research.common.config import repo_path
from research.common.provenance import write_run_metadata

from .figures import headline_scatter, perturbation_bars
from .tables import ablation_table, extraction_table, main_tables, selection_table


def main(argv=None):
    args = base_parser(__doc__, default_config="configs/analysis.yaml").parse_args(argv)
    cfg = setup_run(args)
    a = cfg["analysis"]
    main_dir = repo_path(a["main_dir"])
    prelim = "subset" in str(main_dir)
    fig_dir, tab_dir = repo_path(a["figures_dir"]), repo_path(a["tables_dir"])
    fig_dir.mkdir(parents=True, exist_ok=True)
    tab_dir.mkdir(parents=True, exist_ok=True)
    tag = "_preliminary" if prelim else ""

    metrics = pd.read_csv(main_dir / "metrics.csv")
    tests_f = main_dir / "tests.csv"
    tests = pd.read_csv(tests_f) if tests_f.exists() and tests_f.stat().st_size > 1 else pd.DataFrame()
    pts = headline_scatter(metrics, a, fig_dir / f"headline_accuracy_vs_gap{tag}", prelim)
    perturbation_bars(metrics, a, fig_dir / f"perturbation_gaps{tag}", preliminary=prelim)
    (tab_dir / f"main{tag}.tex").write_text(main_tables(metrics, tests, a, prelim), encoding="utf-8")
    written = [f"figures/headline_accuracy_vs_gap{tag}.(pdf|png)", f"figures/perturbation_gaps{tag}.(pdf|png)",
               f"tables/main{tag}.tex"]

    ext = repo_path(a["extraction_csv"])
    if ext.exists():
        (tab_dir / "extraction.tex").write_text(extraction_table(ext), encoding="utf-8")
        written.append("tables/extraction.tex")
    abl = {k: repo_path(v) for k, v in a["ablation_dirs"].items()}
    if any((d / "metrics.csv").exists() for d in abl.values()):
        abl_prelim = any("subset" in str(d) for d in abl.values())
        (tab_dir / f"ablations{tag}.tex").write_text(ablation_table(abl, a, abl_prelim), encoding="utf-8")
        written.append(f"tables/ablations{tag}.tex")
    sel = repo_path(a["selection_dir"])
    if (sel / "metrics.csv").exists():
        ours_variant = cfg.get("selection_choice")
        (tab_dir / "selection.tex").write_text(selection_table(sel, ours_variant), encoding="utf-8")
        written.append("tables/selection.tex")

    idx = ["# Paper outputs", "", f"Generated by `python -m research.analysis.make_all` from `{a['main_dir']}`"
           + (" (PRELIMINARY subset run)" if prelim else "") + ".", ""]
    idx += [f"- `{w}`" for w in written]
    idx += ["", "Headline points (x = nDCG@10, y = |gap| under the full gender flip):", "",
            "| scorer | nDCG@10 | gap |", "|---|---|---|"]
    idx += [f"| {r.scorer} | {r.x:.3f} | {r.y:.3f} |" for r in pts.itertuples()]
    (repo_path(a["figures_dir"]).parent / "README.md").write_text("\n".join(idx) + "\n", encoding="utf-8")
    write_run_metadata(repo_path(cfg["paths"]["results"]) / "analysis", cfg, extra={"written": written})
    print("\n".join(idx))


if __name__ == "__main__":
    main()
